version: "3.9"
services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    container_name: dockdbtest_container
    restart: always
    environment:
      POSTGRES_DB: dockdbtest
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - "C:/Users/dejol/Documents/postgress:/var/lib/postgresql/data"
    ports:
      - "5432:5432"

  fastapi_one:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    container_name: fastapi_one_container
    restart: always
    ports:
      - "8000:8000" # Maps FastAPI to host port 8000
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: dockdbtest
      POSTGRES_USER: api_one
      POSTGRES_PASSWORD: password_one

  fastapi_two:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    container_name: fastapi_two_container
    restart: always
    ports:
      - "8001:8000" # Maps FastAPI to host port 8001
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: dockdbtest
      POSTGRES_USER: api_two
      POSTGRES_PASSWORD: password_two