services:
  postgres:
    build:
      context: .
      dockerfile: docker/Dockerfile.postgres
    container_name: dockdbtest_container
    restart: always
    environment:
      POSTGRES_DB: dockdbtest
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - "./postgres/db:/var/lib/postgresql/data"
    ports:
      - "5432:5432"

  fastapi_one:
    build:
      context: .
      dockerfile: docker/Dockerfile.fastapi
    container_name: fastapi_one_container
    restart: always
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: dockdbtest
      POSTGRES_USER: api_one
      POSTGRES_PASSWORD: password_one
    ports:
      - "8000:8000"

  fastapi_two:
    build:
      context: .
      dockerfile: docker/Dockerfile.fastapi
    container_name: fastapi_two_container
    restart: always
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: dockdbtest
      POSTGRES_USER: api_two
      POSTGRES_PASSWORD: password_two
    ports:
      - "8001:8000"

  nginx:
    build:
      context: .
      dockerfile: docker/Dockerfile.nginx
    container_name: nginx_load_balancer
    restart: always
    depends_on:
      - fastapi_one
      - fastapi_two
    ports:
      - "8080:80"