# Use the official Python image
FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Copy application files
COPY ../app /app/app

# Install dependencies
RUN pip install --no-cache-dir -r /app/app/requirements.txt

# Expose the port for the app
EXPOSE 8000

# Run the application
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]