# Use the official Nginx image as the base
FROM nginx:latest

# Set working directory in the container
WORKDIR /etc/nginx

# Copy the custom Nginx configuration file to the container
COPY ../nginx/nginx.conf /etc/nginx/nginx.conf

# Expose the port that Nginx listens on
EXPOSE 80